// <auto-generated />
namespace Consultoresvs3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migracionproyectos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migracionproyectos));
        
        string IMigrationMetadata.Id
        {
            get { return "201709201619277_migracionproyectos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
